"""Add category column to post table

Revision ID: 3cc24b74f268
Revises: dc627a995e10
Create Date: 2025-02-22 01:26:45.310752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc24b74f268'
down_revision = 'dc627a995e10'
branch_labels = None
depends_on = None


def upgrade():
    # Drop the temporary table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_post")

    # Create a new table with the 'category' column
    with op.batch_alter_table('post') as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='general'))  # Add default value
        batch_op.drop_column('template')  # Drop the old column if it exists


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
