from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7864410279ce'
down_revision = 'bc84e647a4bb'
branch_labels = None
depends_on = None

def upgrade():
    # Step 1: Add a default value to the `chain` column for rows where it is NULL
    op.execute("UPDATE NFT SET chain = 'ethereum' WHERE chain IS NULL")

    # Step 2: Alter the `chain` column to be non-nullable
    with op.batch_alter_table('NFT', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('seller',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('chain',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NFT', schema=None) as batch_op:
        batch_op.alter_column('chain',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('owner',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('seller',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)