"""Add upvotes and downvotes to Post model

Revision ID: dc627a995e10
Revises: 9d3af24341ab
Create Date: 2025-02-16 02:40:52.670238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc627a995e10'
down_revision = '9d3af24341ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('template', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('template')
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
